name: molgen-csa
channels:
  - pytorch
  - dglteam
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - pytorch=1.13
  - pytorch-cuda=11.6
  - dgl-cuda11.6=0.9
  - rdkit
  - numpy
  - scipy
  - scikit-learn
  - pandas
